/home/zcw7438/.local/lib/python3.6/site-packages/pandas/compat/_optional.py:106: UserWarning: Pandas requires version '1.2.1' or newer of 'bottleneck' (version '1.2.0' currently installed).
  warnings.warn(msg, UserWarning)
         dma_code_month  dma_code  ... mint  chocolate
0            529 200601       529  ...    0          0
1            529 200603       529  ...    0          0
3            618 200601       618  ...    0          0
4            640 200602       640  ...    0          0
6            693 200603       693  ...    0          0
...                 ...       ...  ...  ...        ...
26461612     577 200712       577  ...    0          0
26461613     577 200801       577  ...    0          0
26461614     577 200802       577  ...    0          0
26461615     577 200803       577  ...    0          0
26461616     577 200804       577  ...    0          0

[15581665 rows x 11 columns]
          dma_code_month  dma_code  ...   mint  chocolate
0                  False     False  ...  False      False
1                  False     False  ...  False      False
3                  False     False  ...  False      False
4                  False     False  ...  False      False
6                  False     False  ...  False      False
...                  ...       ...  ...    ...        ...
26461612           False     False  ...  False      False
26461613           False     False  ...  False      False
26461614           False     False  ...  False      False
26461615           False     False  ...  False      False
26461616           False     False  ...  False      False

[15581665 rows x 11 columns]
Empty DataFrame
Columns: [dma_code_month, dma_code, owner initial, log_adjusted_price, upc, market_share, distance, sugar, cocoa_beans, mint, chocolate]
Index: []
Initializing the problem ...
Traceback (most recent call last):
  File "plainLogit.py", line 37, in <module>
    GenerateDEData(products, quarterOrMonth, inputs, characteristics)
  File "plainLogit.py", line 23, in GenerateDEData
    problem = pyblp.Problem(logit_formulation, demand_estimation_data)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pyblp/economies/problem.py", line 1193, in __init__
    products = Products(product_formulations, product_data, add_exogenous=add_exogenous)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pyblp/primitives.py", line 140, in __new__
    raise KeyError("product_data must have a market_ids field.")
KeyError: 'product_data must have a market_ids field.'
